using System;
using UnityEngine;
using UnityEngine.Experimental.Rendering;
using XrSpatial.Core;

namespace XrSpatial.Capture
{
    /// <summary>
    /// A live captured source: owns the backend, the upload texture and the mip-mapped view texture that panels sample. Many panels (full and cropped) share one
    /// source. Call <see cref="Tick"/> once per frame. Restarts window sources that end (the game was relaunched) every couple of seconds.
    /// </summary>
    public sealed class ScreenSource : IDisposable
    {
        public readonly SourceDef Def;
        public ICaptureBackend Backend { get; private set; }
        public RenderTexture View { get; private set; }
        public int Width => View ? View.width : 0;
        public int Height => View ? View.height : 0;
        public float Aspect => View && View.height > 0 ? (float)View.width / View.height : 16f / 9f;
        public bool HasFrame => View != null;
        public long FrameCount { get; private set; }
        public WindowGeometry Window => Backend != null ? Backend.Window : default;
        /// <summary>True from the moment a source that had shown frames ends (window closed, PC host gone) until a new frame arrives; panels dim and say so instead of freezing on the last picture.</summary>
        public bool Closed { get; private set; }
        long m_ClosedAtFrame;
        public string Status => Backend != null ? Backend.Status : "not started";
        /// <summary>The depth map of this source (Depth Lab), or null when the backend has none. Never touched while depth is off.</summary>
        bool IsSynthetic => Def.kind == "pattern" || Def.kind == "depthtest";                    // generated locally: never "closed", nothing to reconnect
        public Texture2D DepthMap => (Backend as IDepthProvider)?.Depth ?? (IsSynthetic ? null : DepthProfiles.LiveTexture);

        readonly Func<CaptureRequest> m_Request;
        Texture2D m_Raw;
        float m_RetryAt;

        public ScreenSource(SourceDef def, Func<CaptureRequest> request)
        {
            Def = def; m_Request = request;
            Restart();
        }

        public void Restart()
        {
            Backend?.Dispose();
            Backend = null;
            if (Def.kind == "pattern") Backend = new PatternBackend();
            else if (Def.kind == "depthtest") Backend = new DepthTestBackend();
            else if (RemoteHost.Active)
            {
                // headset build: the PC host streams the window; find it by process/title among the PC's windows (retried by Tick while it is not open)
                var win = Def.kind == "window" ? RemoteHost.Resolve(Def.processName, Def.titleContains) : null;
                if (win != null) Backend = new NetworkBackend(win.hwnd);
            }
            else
            {
                var req = m_Request?.Invoke();
                if (req == null) return;
                Backend = new SidecarBackend(req);
            }
        }

        public void Tick()
        {
            if (Closed && FrameCount > m_ClosedAtFrame) Closed = false;
            if (Backend == null)
            {
                if (!Closed && FrameCount > 0 && !IsSynthetic) { Closed = true; m_ClosedAtFrame = FrameCount; }
                if (!IsSynthetic && Time.realtimeSinceStartup > m_RetryAt) { m_RetryAt = Time.realtimeSinceStartup + 2f; Restart(); }
                return;
            }
            if (Backend.PollInto(ref m_Raw) && m_Raw)
            {
                EnsureView(m_Raw.width, m_Raw.height);
                // The capture helper writes the top row first (what the panel shader expects); a decoded JPEG has its bottom row first, so flip it on the GPU.
                if (Backend is NetworkBackend nb && nb.NeedsFlip) Graphics.Blit(m_Raw, View, new Vector2(1f, -1f), new Vector2(0f, 1f));
                else Graphics.Blit(m_Raw, View);
                FrameCount++;
            }
            if (!Closed && FrameCount > 0 && !IsSynthetic && Backend.HasEnded) { Closed = true; m_ClosedAtFrame = FrameCount; }
            if (Backend.HasEnded && !IsSynthetic && Time.realtimeSinceStartup > m_RetryAt)
            {
                m_RetryAt = Time.realtimeSinceStartup + 2f;
                Restart();
            }
        }

        void EnsureView(int w, int h)
        {
            if (View && View.width == w && View.height == h) return;
            if (View) { View.Release(); UnityEngine.Object.Destroy(View); }
            // sRGB, mip-mapped and anisotropic: steeply angled and distant screens stay sharp and do not shimmer. Mips are regenerated by the GPU on every blit.
            var desc = new RenderTextureDescriptor(w, h, GraphicsFormat.B8G8R8A8_SRGB, 0) { useMipMap = true, autoGenerateMips = true, mipCount = -1 };
            View = new RenderTexture(desc) { name = "Source-" + Def.id, filterMode = FilterMode.Trilinear, anisoLevel = 8, wrapMode = TextureWrapMode.Clamp };
            View.Create();
        }

        public void Dispose()
        {
            Backend?.Dispose(); Backend = null;
            if (View) { View.Release(); UnityEngine.Object.Destroy(View); }
            if (m_Raw) UnityEngine.Object.Destroy(m_Raw);
        }
    }
}
